on: push
name: Publish to Netlify if changed
jobs:
  checkChangesInPosts:
    name: Check for changes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check changes in stories
      uses: netlify/actions/diff-includes@master
      with:
        args: _src
